version: '3.8'

services:

  #  The Application
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app_dev"
      - "MYSQL_USER=app_user"
      - "MYSQL_PASSWORD=app_pass"
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - 3306:3306

volumes:
  dbdata:
